guests = ['tom', 'blair', 'mel']
print(f"Hello {guests[0].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-1].title()}, would you like to attend a dinner with me?")
declined = guests.pop(1)
guests.append('susan')
print(f"Hello {guests[0].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-1].title()}, would you like to attend a dinner with me?")
print(f"{declined.title()} has informed me that he is unable to make it.")
