guests = ['tom', 'blair', 'mel']
print(f"Hello {guests[0].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-1].title()}, would you like to attend a dinner with me?")
declined = guests.pop(1)
print(f"{declined.title()} has informed me that he is unable to make it.")
guests.append('susan')
print(f"Hello {guests[0].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-1].title()}, would you like to attend a dinner with me?")
print("The restaurant has informed me that they have a larger table.")
guests.insert(0, 'bob')
guests.insert(2, 'jason')
guests.insert(-1, 'steve')
print(f"Hello {guests[2].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[0].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-1].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-2].title()}, would you like to attend a dinner with me?")
print(f"Hello {guests[-3].title()}, would you like to attend a dinner with me?")
